### ISSUE TITLE
Build ros on Ubuntu 21.10

### ISSUE THREAD

**Issue by lucasw** [lucasw/ros_from_src#3]
Have this working in Dockerfile, next do it on a real computer.

```
sudo apt remove ros-noetic*
```

Do this twice, once to get from 20.04 to 21.04, then again to get to 21.10:

```
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo reboot
```
edit TBD file change `lts` to `normal`

```
sudo do-release-upgrade
```

**Comment by lucasw** [comment]
Trying to run roscore, but:

```
$ roscore
WARNING: cannot load logging configuration file, logging is disabled
... logging to /home/lucasw/.ros/log/04b0d0a6-2f98-11ec-a4fa-1fcb894b6118/roslaunch-drjs-44382.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: roslaunch
ROS path [0]=/home/lucasw/own/ros/staging/catkin_ws/src/ros/core/rosbuild
The traceback for the exception was written to the log file
```

`python -c "import roslaunch"` and `roslaunch` from the command line both work.

modify ros_comm to provide the traceback (the reported log file doesn't exist)
```
diff --git a/tools/roslaunch/src/roslaunch/__init__.py b/tools/roslaunch/src/roslaunch/__init__.py
index fcc18ea97..5e9faa531 100644
--- a/tools/roslaunch/src/roslaunch/__init__.py
+++ b/tools/roslaunch/src/roslaunch/__init__.py
@@ -241,7 +241,7 @@ def _validate_args(parser, options, args):
         parser.error("only one of [--nodes, --find-node, --args --ros-args] may be specified")
     
 def handle_exception(roslaunch_core, logger, msg, e):
-    roslaunch_core.printerrlog(msg + str(e))
+    print(traceback.format_exc())
     roslaunch_core.printerrlog('The traceback for the exception was written to the log file')
     if logger:
         logger.error(traceback.format_exc())
```

now
```

Traceback (most recent call last):
  File "<string>", line 347, in main
  File "/home/lucasw/own/ros/staging/catkin_ws/src/ros_comm/tools/roslaunch/src/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/home/lucasw/own/ros/staging/catkin_ws/src/ros_comm/tools/roslaunch/src/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/home/lucasw/own/ros/staging/catkin_ws/src/ros_comm/tools/roslaunch/src/roslaunch/parent.py", line 156, in _load_config
    self.config = roslaunch.config.load_config_default(self.roslaunch_files, self.port,
  File "/home/lucasw/own/ros/staging/catkin_ws/src/ros_comm/tools/roslaunch/src/roslaunch/config.py", line 451, in load_config_default
    load_roscore(loader, config, verbose=verbose)
  File "/home/lucasw/own/ros/staging/catkin_ws/src/ros_comm/tools/roslaunch/src/roslaunch/config.py", line 92, in load_roscore
    f_roscore = get_roscore_filename()
  File "/home/lucasw/own/ros/staging/catkin_ws/src/ros_comm/tools/roslaunch/src/roslaunch/config.py", line 84, in get_roscore_filename
    return os.path.join(r.get_path('roslaunch'), 'resources', 'roscore.xml')
  File "/home/lucasw/own/ros/staging2/ros/lib/python3.9/site-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: roslaunch

```

**Comment by lucasw** [comment]
Need to remove key added by apt-key:

```
sudo apt-key list
pub   rsa4096 2019-05-30 [SC] [expires: 2025-06-01]
...
uid           [ unknown] Open Robotics <info@osrfoundation.org>

sudo apt-key del <last 8 characters of key from list, removed above>
```

**Comment by lucasw** [comment]
Could look at https://github.com/ros/ros-overlay for gentoo ros build instructions

**Comment by lucasw** [comment]
```
+ rosdep init
ERROR: cannot create /etc/ros/rosdep/sources.list.d/20-default.list:
	[Errno 13] Permission denied: '/etc/ros/rosdep/sources.list.d/20-default.list'
```

how to avoid sudo here?

->

```

def get_sources_list_dir():
    # base of where we read config files from
    # TODO: windows
    if 0:
        # we can't use etc/ros because environment config does not carry over under sudo
        etc_ros = rospkg.get_etc_ros_dir()
    else:
        etc_ros = 'etc/ros'
```

**Comment by lucasw** [comment]
```
Errors     << rosconsole:make /home/lucasw/own/ros/staging3/catkin_ws/logs/rosconsole/build.make.000.log
/home/lucasw/own/ros/staging3/catkin_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp: In function ‘void* ros::console::impl::getHandle(const string&)’:
/home/lucasw/own/ros/staging3/catkin_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp:205:43: error: ‘log4cxx::LoggerPtr’ {aka ‘class log4cxx::helpers::ObjectPtrT<log4cxx::Logger>’} has no member named ‘get’
  205 |   return log4cxx::Logger::getLogger(name).get();
      |                                           ^~~
/home/lucasw/own/ros/staging3/catkin_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp: In function ‘bool ros::console::impl::get_loggers(std::map<std::__cxx11::basic_string<char>, ros::console::levels::Level>&)’:
/home/lucasw/own/ros/staging3/catkin_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp:221:123: error: ‘log4cxx::spi::LoggerRepositoryPtr’ {aka ‘class log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggerRepository>’} has no member named ‘lock’
  221 |   log4cxx::spi::LoggerRepositoryPtr repo = log4cxx::Logger::getLogger(ROSCONSOLE_ROOT_LOGGER_NAME)->getLoggerRepository().lock();
      |                                                                                                                           ^~~~
/home/lucasw/own/ros/staging3/catkin_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp: In function ‘void ros::console::impl::shutdown()’:
/home/lucasw/own/ros/staging3/catkin_ws/src/rosconsole/src/rosconsole/impl/rosconsole_log4cxx.cpp:388:59: error: ‘log4cxx::spi::LoggerRepositoryPtr’ {aka ‘class log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggerRepository>’} has no member named ‘lock’
  388 |   log4cxx::Logger::getRootLogger()->getLoggerRepository().lock()->shutdown();
      |                                                           ^~~~
make[2]: *** [CMakeFiles/rosconsole_log4cxx.dir/build.make:82: CMakeFiles/rosconsole_log4cxx.dir/src/rosconsole/impl/rosconsole_log4cxx.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:370: CMakeFiles/rosconsole_log4cxx.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```


Need to unwind rosconsole, roll back before
```
 5b072a5d5a27bb74b6463d1720560aa5e2524828
Author: Achmad Fathoni <fathoni.id@gmail.com>
Date:   Sun Aug 15 19:48:13 2021 +0700

    Fix for log4cxx 0.12.0
```

**Comment by lucasw** [comment]
Looks to be mostly working in 21.10, need to have this in .bashrc
```
export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DEST:$HOME/own/ros/staging3/ros/lib/cmake
export PYTHONPATH=$PYTHONPATH:$HOME/own/ros/staging3/ros/lib/python3.9/site-packages/
source $HOME/own/ros/staging3/ros/setup.bash
```
